"""
compiler/operators/gpl_operators.py
=====================================
GPL operator library — the computation engine for Branch A compilation.

Each operator is a pure function:
  - Takes declarative arguments (atom canonical_id, agg type, column, filters, etc.)
  - Reads data only from the CSV root set by build_namespace()
  - Returns a dict with at minimum: {oracle_value, formula_line}
  - Never modifies any file or global state

OPERATORS IN THIS FILE:
  MEASURE                   — simple aggregation, no time window, no dedup
  MEASURE_SNAPSHOT_DEDUPED  — state-table dedup (dedup THEN filter)
  MEASURE_MONTH_FIXED       — this_month / last_month
  MEASURE_QUARTER_FIXED     — this_quarter / last_quarter / this_year / last_year
  MEASURE_YTD               — year to date (Jan 1 → today)
  MEASURE_GROUPED           — grouped by dimension or time bucket
                              supports in-memory FK join for cross-table goals

ADDING NEW OPERATORS:
  New operators should be added in this file following the same pattern:
    1. Decorate with @gpl_operator
    2. Implement computation only — do NOT build formula strings manually
    3. Return {"oracle_value": value, ...} — formula_line is injected automatically
    4. Register the new function in build_namespace() below

  The @gpl_operator decorator auto-generates an executable formula_line from the
  actual arguments the operator was called with. New operators get this for free.

EXECUTION MODEL:
  Branch A builds a formula_line string by calling the operator via @gpl_operator.
  The compiler exec()s that string against a namespace built by build_namespace().
  The operator runs, and the oracle_value is extracted from the namespace.

  formula_line IS the executable artifact — it gets stored in the aterm and
  shipped to the customer runtime, where it executes against real data using
  the same operator functions registered in build_namespace().
"""

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import numpy as np

from compiler.operators.gpl_operator_decorator import gpl_operator
from compiler.operators._csv_loader import (
    set_csv_root, load_csv, apply_filters, aggregate, dedup_latest_per_key,
)
from compiler.operators._time_helpers import (
    current_year_month, previous_year_month,
    current_quarter, previous_quarter,
    quarter_date_range, year_date_range,
    filter_by_month, filter_by_range, filter_ytd,
    bucket_date_key, now_utc,
)

log = logging.getLogger(__name__)


# ── MEASURE ───────────────────────────────────────────────────────────────────

@gpl_operator
def MEASURE(
    atom_canonical_id: str,
    agg: str,
    column: Optional[str],
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Simple aggregation over an atom's rows. No time window, no dedup.

    Used for:
      - Dimension tables (customers) — no state snapshots, no time needed
      - Record tables with time=all_time and no grouping
      - Max/min goals (Wave 2)

    Args:
        atom_canonical_id: canonical_id of the atom (= CSV filename stem)
        agg:               COUNT_DISTINCT | COUNT | SUM | AVG | MAX | MIN
        column:            column to aggregate; None is valid only for COUNT(*) types
        filters:           optional [{field, op, value}] predicates

    Returns:
        {oracle_value: float, row_count: int, formula_line: str}
        formula_line is auto-generated by @gpl_operator decorator.
    """
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    value    = aggregate(filtered, agg, column)

    return {
        "oracle_value": value,
        "row_count":    len(filtered),
    }


# ── MEASURE_SNAPSHOT_DEDUPED ──────────────────────────────────────────────────

@gpl_operator
def MEASURE_SNAPSHOT_DEDUPED(
    atom_canonical_id: str,
    dedup_sort_col: str,
    grain_keys: List[str],
    agg: str,
    column: Optional[str],
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Dedup-then-aggregate for state-type atoms.

    State tables record every status change for an entity (e.g. an order
    that moves from Processing → Shipped → Completed appears as 3 rows).
    We always want the CURRENT state — so we dedup to the latest row per
    grain_key BEFORE applying any filter.

    CRITICAL ORDER (from the doc):
      dedup → filter → aggregate
      NOT: filter → dedup (this silently gives wrong counts)

    Example: "How many Completed orders?"
      Wrong (filter first): keep only Completed rows, then dedup
        → may count old Completed snapshots for orders now Cancelled
      Correct (dedup first): keep latest row per order_id, then filter for Completed
        → counts only orders whose CURRENT state is Completed

    Args:
        atom_canonical_id: which atom to read
        dedup_sort_col:    column used to determine "latest" (usually a date/timestamp)
        grain_keys:        columns that uniquely identify one entity (e.g. ["order_id"])
        agg:               aggregation type
        column:            column to aggregate
        filters:           applied AFTER dedup

    Returns:
        {oracle_value, row_count, dedup_count, formula_line}
    """
    rows     = load_csv(atom_canonical_id)
    deduped  = dedup_latest_per_key(rows, dedup_sort_col, grain_keys)
    filtered = apply_filters(deduped, filters)
    value    = aggregate(filtered, agg, column)

    return {
        "oracle_value": value,
        "row_count":    len(filtered),
        "dedup_count":  len(deduped),
    }


# ── MEASURE_SNAPSHOT_DEDUPED_MONTH ───────────────────────────────────────────

@gpl_operator
def MEASURE_SNAPSHOT_DEDUPED_MONTH(
    atom_canonical_id: str,
    date_col: str,
    dedup_sort_col: str,
    grain_keys: List[str],
    agg: str,
    column: Optional[str],
    which_month: str = "this_month",
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Time-scoped dedup-then-aggregate for state-type atoms.

    For state tables with a time window: filter to the month first,
    then dedup to the latest snapshot within that month, then aggregate.

    Order: time_filter → dedup_within_window → state_filter → aggregate

    Example: "Total quantity_on_hand this month"
      1. Keep only rows where snapshot_date is in this month
      2. Dedup to latest snapshot per inventory_id within this month
      3. SUM(quantity_on_hand) on the deduped rows
    """
    rows = load_csv(atom_canonical_id)

    if which_month == "last_month":
        year, month = previous_year_month()
    else:
        year, month = current_year_month()

    scoped   = filter_by_month(rows, date_col, year, month)
    deduped  = dedup_latest_per_key(scoped, dedup_sort_col, grain_keys)
    filtered = apply_filters(deduped, filters)
    value    = aggregate(filtered, agg, column)

    return {
        "oracle_value": value,
        "row_count":    len(filtered),
        "dedup_count":  len(deduped),
        "year":         year,
        "month":        month,
    }


# ── MEASURE_SNAPSHOT_DEDUPED_QUARTER ─────────────────────────────────────────

@gpl_operator
def MEASURE_SNAPSHOT_DEDUPED_QUARTER(
    atom_canonical_id: str,
    date_col: str,
    dedup_sort_col: str,
    grain_keys: List[str],
    agg: str,
    column: Optional[str],
    which: str = "this_quarter",
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Quarter-scoped dedup-then-aggregate for state-type atoms.
    Order: time_filter → dedup_within_window → state_filter → aggregate
    """
    rows = load_csv(atom_canonical_id)

    if which == "this_quarter":
        year, q = current_quarter()
        start, end = quarter_date_range(year, q)
        period_label = f"{year}-Q{q}"
    elif which == "last_quarter":
        year, q = previous_quarter()
        start, end = quarter_date_range(year, q)
        period_label = f"{year}-Q{q}"
    elif which == "this_year":
        year = now_utc().year
        start, end = year_date_range(year)
        period_label = str(year)
        q = None
    elif which == "last_year":
        year = now_utc().year - 1
        start, end = year_date_range(year)
        period_label = str(year)
        q = None
    else:
        raise ValueError(f"MEASURE_SNAPSHOT_DEDUPED_QUARTER: unknown scope '{which}'")

    scoped   = filter_by_range(rows, date_col, start, end)
    deduped  = dedup_latest_per_key(scoped, dedup_sort_col, grain_keys)
    filtered = apply_filters(deduped, filters)
    value    = aggregate(filtered, agg, column)

    result = {
        "oracle_value": value,
        "row_count":    len(filtered),
        "dedup_count":  len(deduped),
        "period":       period_label,
        "year":         year,
    }
    if "q" in dir() and q is not None:
        result["quarter"] = q
    return result


# ── MEASURE_SNAPSHOT_DEDUPED_YTD ─────────────────────────────────────────────

@gpl_operator
def MEASURE_SNAPSHOT_DEDUPED_YTD(
    atom_canonical_id: str,
    date_col: str,
    dedup_sort_col: str,
    grain_keys: List[str],
    agg: str,
    column: Optional[str],
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    YTD-scoped dedup-then-aggregate for state-type atoms.
    Order: time_filter → dedup_within_window → state_filter → aggregate
    """
    rows  = load_csv(atom_canonical_id)
    today = now_utc()
    start = today.replace(month=1, day=1)

    scoped   = filter_by_range(rows, date_col, start, today)
    deduped  = dedup_latest_per_key(scoped, dedup_sort_col, grain_keys)
    filtered = apply_filters(deduped, filters)
    value    = aggregate(filtered, agg, column)

    return {
        "oracle_value": value,
        "row_count":    len(filtered),
        "dedup_count":  len(deduped),
        "year":         today.year,
    }


# ── MEASURE_MONTH_FIXED ───────────────────────────────────────────────────────

@gpl_operator
def MEASURE_MONTH_FIXED(
    atom_canonical_id: str,
    date_col: str,
    agg: str,
    column: Optional[str],
    which_month: str = "this_month",
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Aggregation scoped to a fixed calendar month.

    which_month: "this_month" | "last_month"

    Time window is applied BEFORE state filters — we want rows from this
    month that match the filter, not all matching rows then scoped to month.
    (For non-state tables the order doesn't matter; for state tables the
    caller should use MEASURE_SNAPSHOT_DEDUPED_MONTH if dedup is also needed,
    but our decision tree currently routes state+time to ROUTE_LLM_WIZARD
    until that operator is built.)
    """
    rows = load_csv(atom_canonical_id)

    if which_month == "last_month":
        year, month = previous_year_month()
    else:
        year, month = current_year_month()

    scoped   = filter_by_month(rows, date_col, year, month)
    filtered = apply_filters(scoped, filters)
    value    = aggregate(filtered, agg, column)

    return {
        "oracle_value": value,
        "row_count":    len(filtered),
        "year":         year,
        "month":        month,
    }


# ── MEASURE_QUARTER_FIXED ─────────────────────────────────────────────────────

@gpl_operator
def MEASURE_QUARTER_FIXED(
    atom_canonical_id: str,
    date_col: str,
    agg: str,
    column: Optional[str],
    which: str = "this_quarter",
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Aggregation scoped to a calendar quarter or full calendar year.

    which: "this_quarter" | "last_quarter" | "this_year" | "last_year"
    """
    rows = load_csv(atom_canonical_id)

    if which == "this_quarter":
        year, q = current_quarter()
        start, end = quarter_date_range(year, q)
        period_label = f"{year}-Q{q}"
    elif which == "last_quarter":
        year, q = previous_quarter()
        start, end = quarter_date_range(year, q)
        period_label = f"{year}-Q{q}"
    elif which == "this_year":
        year = now_utc().year
        start, end = year_date_range(year)
        period_label = str(year)
        q = None
    elif which == "last_year":
        year = now_utc().year - 1
        start, end = year_date_range(year)
        period_label = str(year)
        q = None
    else:
        raise ValueError(f"MEASURE_QUARTER_FIXED: unknown time scope '{which}'")

    scoped   = filter_by_range(rows, date_col, start, end)
    filtered = apply_filters(scoped, filters)
    value    = aggregate(filtered, agg, column)

    result = {
        "oracle_value": value,
        "row_count":    len(filtered),
        "period":       period_label,
        "year":         year,
    }
    if q is not None:
        result["quarter"] = q
    return result


# ── MEASURE_YTD ───────────────────────────────────────────────────────────────

@gpl_operator
def MEASURE_YTD(
    atom_canonical_id: str,
    date_col: str,
    agg: str,
    column: Optional[str],
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Year-to-date aggregation: Jan 1 of the current year through today.
    """
    rows = load_csv(atom_canonical_id)
    now  = now_utc()

    scoped   = filter_ytd(rows, date_col)
    filtered = apply_filters(scoped, filters)
    value    = aggregate(filtered, agg, column)

    return {
        "oracle_value": value,
        "row_count":    len(filtered),
        "start_date":   f"{now.year}-01-01",
        "end_date":     str(now.date()),
    }


# ── MEASURE_GROUPED ───────────────────────────────────────────────────────────

@gpl_operator
def MEASURE_GROUPED(
    atom_canonical_id: str,
    agg: str,
    column: Optional[str],
    group_by_col: Optional[str] = None,
    filters: Optional[List[Dict]] = None,
    join_atom_canonical_id: Optional[str] = None,
    join_from_field: Optional[str] = None,
    join_to_field: Optional[str] = None,
    time_bucket: Optional[Dict] = None,
) -> Dict:
    """
    Aggregation grouped by a dimension or time bucket.

    Covers two goal types:
      1. Series goals (Wave 8): group by a calendar bucket derived from a
         date column — pass time_bucket={"date_col": ..., "granularity": "month"}
         instead of group_by_col.

      2. Cross-table goals (Wave 7): group by a column on a JOINED atom —
         pass join_atom_canonical_id + join_from_field + join_to_field.
         The join is an in-memory left-inner join: rows with no FK match
         are excluded (same behaviour as SQL INNER JOIN).

    Args:
        atom_canonical_id:      primary atom to read
        agg:                    aggregation type
        column:                 column to aggregate (on primary atom)
        group_by_col:           column name to group by (may be on joined atom)
        filters:                applied after join and before grouping
        join_atom_canonical_id: secondary atom for FK join (optional)
        join_from_field:        FK column on primary atom (e.g. "customer_id")
        join_to_field:          PK column on secondary atom (e.g. "id")
        time_bucket:            {"date_col": str, "granularity": "month"|"quarter"|...}
                                if set, overrides group_by_col

    Returns:
        {
            oracle_value: dict {group_key: float},   ← breakdown by group
            row_count:    int,
            group_count:  int,
            formula_line: str,
        }
    Note: oracle_value is a DICT for grouped goals, not a single float.
    The aterm stores this as-is; the runtime renders it as a table/chart.
    """
    rows = load_csv(atom_canonical_id)

    # ── In-memory FK join ───────────────────────────────────────────────────
    if join_atom_canonical_id and join_from_field and join_to_field:
        join_rows   = load_csv(join_atom_canonical_id)
        join_lookup = {str(r.get(join_to_field, "")).strip(): r
                       for r in join_rows}

        joined = []
        for r in rows:
            fk_val = str(r.get(join_from_field, "")).strip()
            match  = join_lookup.get(fk_val)
            if match:
                merged = dict(r)
                # Bring joined columns across, without overwriting primary cols
                for k, v in match.items():
                    merged.setdefault(k, v)
                joined.append(merged)

        if not joined:
            log.warning(
                f"[MEASURE_GROUPED] Join produced 0 rows: "
                f"{atom_canonical_id}.{join_from_field} → "
                f"{join_atom_canonical_id}.{join_to_field}"
            )
        rows = joined

    filtered = apply_filters(rows, filters)

    # ── Group and aggregate ─────────────────────────────────────────────────
    groups: Dict[str, List[Dict]] = {}
    for r in filtered:
        if time_bucket:
            key = bucket_date_key(
                r.get(time_bucket["date_col"]),
                time_bucket["granularity"],
            )
        else:
            key = r.get(group_by_col)
        if key is None:
            continue
        groups.setdefault(str(key), []).append(r)

    result = {
        group_key: aggregate(group_rows, agg, column)
        for group_key, group_rows in sorted(groups.items())
    }

    return {
        "oracle_value": result,
        "row_count":    len(filtered),
        "group_count":  len(result),
    }


# ── MEASURE_GROUPED_YTD ───────────────────────────────────────────────────────

@gpl_operator
def MEASURE_GROUPED_YTD(
    atom_canonical_id: str,
    date_col: str,
    agg: str,
    column: Optional[str],
    group_by_col: Optional[str] = None,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Year-to-date aggregation grouped by a dimension column.

    Applies YTD date scoping (Jan 1 of current year → today) BEFORE
    grouping. Combines the time filter of MEASURE_YTD with the
    group-by logic of MEASURE_GROUPED.

    Args:
        atom_canonical_id: canonical_id of the atom
        date_col:          date column used for YTD scoping
        agg:               aggregation type (SUM, COUNT_DISTINCT, AVG, etc.)
        column:            column to aggregate
        group_by_col:      column name to group by
        filters:           additional filters applied after YTD scope

    Returns:
        {
            oracle_value: dict {group_key: float},
            row_count:    int,
            group_count:  int,
            start_date:   str,
            end_date:     str,
        }
    """
    from compiler.operators._time_helpers import filter_ytd
    rows = load_csv(atom_canonical_id)
    now  = now_utc()

    # Apply YTD date scope first
    scoped   = filter_ytd(rows, date_col)
    # Then apply any additional filters (state filters etc.)
    filtered = apply_filters(scoped, filters)

    # Group and aggregate
    groups: Dict[str, List[Dict]] = {}
    for r in filtered:
        key = r.get(group_by_col)
        if key is None:
            continue
        groups.setdefault(str(key), []).append(r)

    result = {
        group_key: aggregate(group_rows, agg, column)
        for group_key, group_rows in sorted(groups.items())
    }

    return {
        "oracle_value": result,
        "row_count":    len(filtered),
        "group_count":  len(result),
        "start_date":   f"{now.year}-01-01",
        "end_date":     str(now.date()),
    }


# ── MEASURE_ROW_RATIO ────────────────────────────────────────────────────────
# Computes numerator_col / denominator_col per row, returns sorted dict.
# Used for "per entity" ratios where both columns live on the same atom.

@gpl_operator
def MEASURE_ROW_RATIO(
    atom_canonical_id: str,
    numerator_col:     str,
    denominator_col:   str,
    label_col:         Optional[str]  = None,
    filters:           Optional[List[Dict]] = None,
    top_n:             int            = 10,
    descending:        bool           = True,
) -> Dict:
    """
    Per-row ratio: numerator_col / denominator_col for each row.

    Returns the top_n rows sorted by ratio (descending by default),
    keyed by label_col (or row index if label_col is None).

    Args:
        atom_canonical_id: canonical_id of the atom
        numerator_col:     column used as numerator
        denominator_col:   column used as denominator
        label_col:         column to use as the output key (e.g. 'buyer_name')
        filters:           optional row filters applied before ratio
        top_n:             how many rows to return (default 10)
        descending:        sort direction (default True = highest ratio first)

    Returns:
        {
            oracle_value: dict {label: ratio, ...},
            row_count:    int,
        }
    """
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)

    ratios = []
    for i, row in enumerate(filtered):
        try:
            num = float(row.get(numerator_col, 0) or 0)
            den = float(row.get(denominator_col, 0) or 0)
            ratio = round(num / den, 6) if den else 0.0
        except (TypeError, ValueError):
            ratio = 0.0
        label = str(row.get(label_col, i)) if label_col else str(i)
        ratios.append((label, ratio))

    ratios.sort(key=lambda x: x[1], reverse=descending)
    result = {label: ratio for label, ratio in ratios[:top_n]}

    return {
        "oracle_value": result,
        "row_count":    len(filtered),
    }


# ── MEASURE_MULTI ─────────────────────────────────────────────────────────────

@gpl_operator
def MEASURE_MULTI(
    atom_canonical_id: str,
    columns: List[Tuple[str, str]],
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Multi-column aggregation over an atom's rows in a single pass.

    Used for composite goals that require multiple aggregations from the
    same table in one formula — e.g. "show gross, discount, tax, and net
    amounts across all invoices."

    Args:
        atom_canonical_id: canonical_id of the atom
        columns:           list of (agg, column) tuples, e.g.
                           [("SUM", "gross_amount"), ("SUM", "discount_amount")]
        filters:           optional [{field, op, value}] predicates

    Returns:
        {
            oracle_value: dict {column_name: float},  ← one value per column
            row_count:    int,
            formula_line: str,                        ← auto-injected by decorator
        }
    """
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)

    result = {}
    for agg, col in columns:
        result[col] = aggregate(filtered, agg, col)

    return {
        "oracle_value": result,
        "row_count":    len(filtered),
    }


# ── MEASURE_MULTI_GROUPED ────────────────────────────────────────────────────

@gpl_operator
def MEASURE_MULTI_GROUPED(
    atom_canonical_id: str,
    columns: List[Tuple[str, str]],
    group_by_col: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Multi-column aggregation grouped by a dimension — single CSV pass.

    Used for composite goals that need both grouping AND multiple aggregations
    — e.g. "show count and freight cost broken down by shipment status."

    Args:
        atom_canonical_id: canonical_id of the atom
        columns:           list of (agg, column) tuples
        group_by_col:      column to group by
        filters:           optional [{field, op, value}] predicates

    Returns:
        {
            oracle_value: dict {group_key: {column_name: float}},
            row_count:    int,
            group_count:  int,
            formula_line: str,
        }
    """
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)

    groups: Dict[str, List[Dict]] = {}
    for r in filtered:
        key = r.get(group_by_col)
        if key is None:
            continue
        groups.setdefault(str(key), []).append(r)

    result = {}
    for group_key, group_rows in sorted(groups.items()):
        result[group_key] = {
            col: aggregate(group_rows, agg, col)
            for agg, col in columns
        }

    return {
        "oracle_value": result,
        "row_count":    len(filtered),
        "group_count":  len(result),
    }

# ── STATISTICAL DISTRIBUTION OPERATORS ───────────────────────────────────────

def _numeric_vals(rows: List[Dict], column: str) -> List[float]:
    """Extract non-null numeric values from a column."""
    vals = []
    for r in rows:
        v = r.get(column)
        if v is not None:
            try:
                vals.append(float(v))
            except (TypeError, ValueError):
                pass
    return vals


@gpl_operator
def MEASURE_STDDEV(
    atom_canonical_id: str,
    column: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Standard deviation of a numeric column (sample, ddof=1)."""
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    vals     = _numeric_vals(filtered, column)
    value    = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
    return {"oracle_value": value, "row_count": len(filtered)}


@gpl_operator
def MEASURE_CV(
    atom_canonical_id: str,
    column: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Coefficient of variation: stddev / mean (expressed as a ratio)."""
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    vals     = _numeric_vals(filtered, column)
    if len(vals) < 2:
        return {"oracle_value": 0.0, "row_count": len(filtered)}
    mean  = float(np.mean(vals))
    value = float(np.std(vals, ddof=1) / mean) if mean != 0 else 0.0
    return {"oracle_value": value, "row_count": len(filtered)}


@gpl_operator
def MEASURE_IQR(
    atom_canonical_id: str,
    column: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Interquartile range: P75 - P25."""
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    vals     = _numeric_vals(filtered, column)
    value    = float(np.percentile(vals, 75) - np.percentile(vals, 25)) if vals else 0.0
    return {"oracle_value": value, "row_count": len(filtered)}


@gpl_operator
def MEASURE_SKEWNESS(
    atom_canonical_id: str,
    column: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Pearson skewness of a numeric column."""
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    vals     = _numeric_vals(filtered, column)
    if len(vals) < 3:
        return {"oracle_value": 0.0, "row_count": len(filtered)}
    a     = np.array(vals)
    mean  = np.mean(a)
    std   = np.std(a, ddof=1)
    value = float(np.mean(((a - mean) / std) ** 3)) if std != 0 else 0.0
    return {"oracle_value": value, "row_count": len(filtered)}


@gpl_operator
def MEASURE_PERCENTILE_N(
    atom_canonical_id: str,
    column: str,
    n: float,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Nth percentile of a numeric column (e.g. n=75 for P75)."""
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    vals     = _numeric_vals(filtered, column)
    value    = float(np.percentile(vals, n)) if vals else 0.0
    return {"oracle_value": value, "row_count": len(filtered), "percentile": n}


# ── TEMPORAL WINDOW OPERATORS ─────────────────────────────────────────────────

@gpl_operator
def MEASURE_MOVING_AVERAGE(
    atom_canonical_id: str,
    date_col: str,
    column: str,
    periods: int,
    agg: str = "SUM",
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Moving average over the last N calendar months.
    Returns the most recent period's average as a float.
    """
    import pandas as pd

    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    if not filtered:
        return {"oracle_value": 0.0, "row_count": 0}

    df = pd.DataFrame(filtered)
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
    df[column]   = pd.to_numeric(df[column], errors="coerce").fillna(0)
    df["_period"] = df[date_col].dt.to_period("M")

    agg_fn  = "sum" if agg.upper() == "SUM" else "mean"
    monthly = df.groupby("_period")[column].agg(agg_fn).sort_index()
    rolled  = monthly.rolling(window=periods, min_periods=1).mean()
    value   = float(rolled.iloc[-1]) if len(rolled) else 0.0

    return {"oracle_value": value, "row_count": len(filtered), "periods": periods}


@gpl_operator
def MEASURE_RUNNING_TOTAL(
    atom_canonical_id: str,
    date_col: str,
    column: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Cumulative sum of column sorted by date.
    Returns the final (latest) cumulative value.
    """
    import pandas as pd

    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    if not filtered:
        return {"oracle_value": 0.0, "row_count": 0}

    df = pd.DataFrame(filtered)
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
    df[column]   = pd.to_numeric(df[column], errors="coerce").fillna(0)
    df = df.sort_values(date_col)
    value = float(df[column].cumsum().iloc[-1])

    return {"oracle_value": value, "row_count": len(filtered)}


@gpl_operator
def MEASURE_LINEAR_TREND(
    atom_canonical_id: str,
    date_col: str,
    column: str,
    agg: str = "SUM",
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Linear regression slope over monthly aggregated data.
    Returns slope (positive = upward trend, negative = downward).
    """
    import pandas as pd

    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    if not filtered:
        return {"oracle_value": 0.0, "row_count": 0}

    df = pd.DataFrame(filtered)
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
    df[column]   = pd.to_numeric(df[column], errors="coerce").fillna(0)
    df["_period"] = df[date_col].dt.to_period("M")

    agg_fn  = "sum" if agg.upper() == "SUM" else "mean"
    monthly = df.groupby("_period")[column].agg(agg_fn).sort_index()

    if len(monthly) < 2:
        return {"oracle_value": 0.0, "row_count": len(filtered)}

    x     = np.arange(len(monthly), dtype=float)
    y     = monthly.values.astype(float)
    slope = float(np.polyfit(x, y, 1)[0])

    return {"oracle_value": slope, "row_count": len(filtered), "periods_used": len(monthly)}


# ── WINDOW RANK OPERATOR ──────────────────────────────────────────────────────

@gpl_operator
def MEASURE_WINDOW_RANK(
    atom_canonical_id: str,
    rank_col: str,
    entity_col: str,
    entity_value: str,
    agg: str = "SUM",
    filters: Optional[List[Dict]] = None,
    ascending: bool = False,
) -> Dict:
    """
    Rank of a specific entity within its partition.
    Returns rank as float (1.0 = best).
    """
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)

    groups: Dict[str, float] = {}
    for r in filtered:
        key = str(r.get(entity_col, ""))
        try:
            groups[key] = groups.get(key, 0.0) + float(r.get(rank_col, 0) or 0)
        except (TypeError, ValueError):
            pass

    sorted_entities = sorted(groups.items(), key=lambda x: x[1], reverse=not ascending)
    rank = next((i + 1 for i, (k, _) in enumerate(sorted_entities) if k == str(entity_value)), 0)

    return {
        "oracle_value":    float(rank),
        "total_entities":  len(groups),
        "entity_value":    entity_value,
    }


# ── CONCENTRATION OPERATORS ───────────────────────────────────────────────────

def _entity_totals(rows: List[Dict], entity_col: str, measure_col: str) -> List[float]:
    """Aggregate measure_col by entity_col, return sorted list of totals."""
    totals: Dict[str, float] = {}
    for r in rows:
        key = str(r.get(entity_col, ""))
        try:
            totals[key] = totals.get(key, 0.0) + float(r.get(measure_col, 0) or 0)
        except (TypeError, ValueError):
            pass
    return sorted(totals.values())


@gpl_operator
def MEASURE_PARETO_RATIO(
    atom_canonical_id: str,
    entity_col: str,
    measure_col: str,
    top_pct: float = 20.0,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """% of total measure contributed by the top top_pct% of entities."""
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    totals   = _entity_totals(filtered, entity_col, measure_col)

    if not totals or sum(totals) == 0:
        return {"oracle_value": 0.0, "row_count": len(filtered)}

    n_top      = max(1, int(len(totals) * top_pct / 100))
    top_sum    = sum(sorted(totals, reverse=True)[:n_top])
    value      = float(top_sum / sum(totals) * 100)

    return {"oracle_value": value, "row_count": len(filtered), "top_pct": top_pct}


@gpl_operator
def MEASURE_HERFINDAHL(
    atom_canonical_id: str,
    entity_col: str,
    measure_col: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Herfindahl-Hirschman Index: sum of squared market shares (0–1 scale)."""
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    totals   = _entity_totals(filtered, entity_col, measure_col)
    grand    = sum(totals)

    if not totals or grand == 0:
        return {"oracle_value": 0.0, "row_count": len(filtered)}

    shares = [t / grand for t in totals]
    value  = float(sum(s ** 2 for s in shares))

    return {"oracle_value": value, "row_count": len(filtered)}


@gpl_operator
def MEASURE_GINI(
    atom_canonical_id: str,
    entity_col: str,
    measure_col: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Gini coefficient of inequality (0 = perfect equality, 1 = max inequality)."""
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)
    totals   = _entity_totals(filtered, entity_col, measure_col)

    if len(totals) < 2 or sum(totals) == 0:
        return {"oracle_value": 0.0, "row_count": len(filtered)}

    a     = np.array(sorted(totals), dtype=float)
    n     = len(a)
    value = float((2 * np.sum(np.arange(1, n + 1) * a) / (n * np.sum(a))) - (n + 1) / n)

    return {"oracle_value": max(0.0, value), "row_count": len(filtered)}


# ── ENTITY SET OPERATORS ──────────────────────────────────────────────────────

def _entity_set(rows: List[Dict], entity_col: str, date_col: str,
                start: str, end: str) -> set:
    """Return set of entity_col values active within [start, end]."""
    result = set()
    for r in rows:
        d = str(r.get(date_col, ""))
        if start <= d <= end:
            result.add(str(r.get(entity_col, "")))
    return result


@gpl_operator
def MEASURE_SET_NEW(
    atom_canonical_id: str,
    entity_col: str,
    date_col: str,
    window1_start: str,
    window1_end: str,
    window2_start: str,
    window2_end: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Count of entities in window2 that were NOT in window1 (new)."""
    rows = apply_filters(load_csv(atom_canonical_id), filters)
    s1   = _entity_set(rows, entity_col, date_col, window1_start, window1_end)
    s2   = _entity_set(rows, entity_col, date_col, window2_start, window2_end)
    return {"oracle_value": float(len(s2 - s1)), "row_count": len(rows)}


@gpl_operator
def MEASURE_SET_RETAINED(
    atom_canonical_id: str,
    entity_col: str,
    date_col: str,
    window1_start: str,
    window1_end: str,
    window2_start: str,
    window2_end: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Count of entities present in BOTH window1 and window2 (retained)."""
    rows = apply_filters(load_csv(atom_canonical_id), filters)
    s1   = _entity_set(rows, entity_col, date_col, window1_start, window1_end)
    s2   = _entity_set(rows, entity_col, date_col, window2_start, window2_end)
    return {"oracle_value": float(len(s1 & s2)), "row_count": len(rows)}


@gpl_operator
def MEASURE_SET_CHURNED(
    atom_canonical_id: str,
    entity_col: str,
    date_col: str,
    window1_start: str,
    window1_end: str,
    window2_start: str,
    window2_end: str,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """Count of entities in window1 that did NOT appear in window2 (churned)."""
    rows = apply_filters(load_csv(atom_canonical_id), filters)
    s1   = _entity_set(rows, entity_col, date_col, window1_start, window1_end)
    s2   = _entity_set(rows, entity_col, date_col, window2_start, window2_end)
    return {"oracle_value": float(len(s1 - s2)), "row_count": len(rows)}


@gpl_operator
def MEASURE_COHORT_RETENTION(
    atom_canonical_id: str,
    entity_col: str,
    date_col: str,
    cohort_start: str,
    cohort_end: str,
    retention_days: int,
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    % of entities from the cohort window still active after retention_days.
    Returns a percentage float (0–100).
    """
    from datetime import datetime, timedelta

    rows   = apply_filters(load_csv(atom_canonical_id), filters)
    cohort = _entity_set(rows, entity_col, date_col, cohort_start, cohort_end)

    if not cohort:
        return {"oracle_value": 0.0, "cohort_size": 0, "row_count": len(rows)}

    try:
        ret_start = cohort_end
        ret_end   = (datetime.strptime(cohort_end, "%Y-%m-%d") +
                     timedelta(days=retention_days)).strftime("%Y-%m-%d")
    except ValueError:
        return {"oracle_value": 0.0, "cohort_size": len(cohort), "row_count": len(rows)}

    retained = _entity_set(rows, entity_col, date_col, ret_start, ret_end)
    value    = float(len(cohort & retained) / len(cohort) * 100)

    return {
        "oracle_value":    value,
        "cohort_size":     len(cohort),
        "retained_count":  len(cohort & retained),
        "row_count":       len(rows),
    }


# ── CORRELATION OPERATOR ──────────────────────────────────────────────────────

@gpl_operator
def MEASURE_CORRELATION(
    atom_canonical_id: str,
    col_a: str,
    col_b: str,
    method: str = "pearson",
    filters: Optional[List[Dict]] = None,
) -> Dict:
    """
    Pearson or Spearman correlation between two columns in the same table.
    Returns coefficient in [-1.0, 1.0].
    """
    rows     = load_csv(atom_canonical_id)
    filtered = apply_filters(rows, filters)

    pairs = []
    for r in filtered:
        try:
            a = float(r.get(col_a, None))
            b = float(r.get(col_b, None))
            pairs.append((a, b))
        except (TypeError, ValueError):
            pass

    if len(pairs) < 2:
        return {"oracle_value": 0.0, "row_count": len(filtered)}

    a_arr = np.array([p[0] for p in pairs])
    b_arr = np.array([p[1] for p in pairs])

    if method == "spearman":
        from scipy.stats import spearmanr
        coeff, _ = spearmanr(a_arr, b_arr)
    else:
        coeff = float(np.corrcoef(a_arr, b_arr)[0, 1])

    return {"oracle_value": float(coeff), "row_count": len(filtered), "method": method}


# ── build_namespace ───────────────────────────────────────────────────────────

def build_namespace(csv_root: str) -> Dict[str, Any]:
    """
    Build the execution namespace for Branch A formula evaluation.

    The compiler calls:
        ns = build_namespace(csv_root)
        exec(formula_line, ns)
        oracle_value = ns["__result__"]

    Every operator function is registered in this namespace so that
    formula_line strings like:
        __result__ = MEASURE('supply_chain_orders_ERP_record', 'COUNT_DISTINCT', 'order_id')
    can be exec()d directly.

    Args:
        csv_root: path to the mock_data root directory (contains vertical subfolders)

    Returns:
        dict mapping operator names to functions, plus CSV_ROOT for reference.
    """
    set_csv_root(Path(csv_root))

    return {
        # ── Operator functions ──────────────────────────────────────────
        "MEASURE":                          MEASURE,
        "MEASURE_SNAPSHOT_DEDUPED":         MEASURE_SNAPSHOT_DEDUPED,
        "MEASURE_SNAPSHOT_DEDUPED_MONTH":   MEASURE_SNAPSHOT_DEDUPED_MONTH,
        "MEASURE_SNAPSHOT_DEDUPED_QUARTER": MEASURE_SNAPSHOT_DEDUPED_QUARTER,
        "MEASURE_SNAPSHOT_DEDUPED_YTD":     MEASURE_SNAPSHOT_DEDUPED_YTD,
        "MEASURE_MONTH_FIXED":              MEASURE_MONTH_FIXED,
        "MEASURE_QUARTER_FIXED":            MEASURE_QUARTER_FIXED,
        "MEASURE_YTD":                      MEASURE_YTD,
        "MEASURE_GROUPED":                  MEASURE_GROUPED,
        "MEASURE_GROUPED_YTD":              MEASURE_GROUPED_YTD,
        "MEASURE_ROW_RATIO":                MEASURE_ROW_RATIO,
        "MEASURE_MULTI":                    MEASURE_MULTI,
        "MEASURE_MULTI_GROUPED":            MEASURE_MULTI_GROUPED,

        # ── Statistical distribution ────────────────────────────────────
        "MEASURE_STDDEV":                   MEASURE_STDDEV,
        "MEASURE_CV":                       MEASURE_CV,
        "MEASURE_IQR":                      MEASURE_IQR,
        "MEASURE_SKEWNESS":                 MEASURE_SKEWNESS,
        "MEASURE_PERCENTILE_N":             MEASURE_PERCENTILE_N,

        # ── Temporal window ─────────────────────────────────────────────
        "MEASURE_MOVING_AVERAGE":           MEASURE_MOVING_AVERAGE,
        "MEASURE_RUNNING_TOTAL":            MEASURE_RUNNING_TOTAL,
        "MEASURE_LINEAR_TREND":             MEASURE_LINEAR_TREND,

        # ── Window rank ─────────────────────────────────────────────────
        "MEASURE_WINDOW_RANK":              MEASURE_WINDOW_RANK,

        # ── Concentration ───────────────────────────────────────────────
        "MEASURE_PARETO_RATIO":             MEASURE_PARETO_RATIO,
        "MEASURE_HERFINDAHL":               MEASURE_HERFINDAHL,
        "MEASURE_GINI":                     MEASURE_GINI,

        # ── Entity set ──────────────────────────────────────────────────
        "MEASURE_SET_NEW":                  MEASURE_SET_NEW,
        "MEASURE_SET_RETAINED":             MEASURE_SET_RETAINED,
        "MEASURE_SET_CHURNED":              MEASURE_SET_CHURNED,
        "MEASURE_COHORT_RETENTION":         MEASURE_COHORT_RETENTION,

        # ── Correlation ─────────────────────────────────────────────────
        "MEASURE_CORRELATION":              MEASURE_CORRELATION,

        # ── Constants available in formula strings ──────────────────────
        "CSV_ROOT": str(csv_root),

        # ── Builtins needed for any exec'd formula ──────────────────────
        "__builtins__": {},
    }


# ── Internal helpers ──────────────────────────────────────────────────────────
# (No manual formula helpers needed — @gpl_operator handles formula_line automatically)
